SUCCESS = 0

USAGE_ERROR = 1  # User requested a usage explanation
FILE_NOT_FOUND = 2
FILE_TOO_BIG = 3
ILLEGAL_OPTION = 4  # Illegal command line option
INI_FILENAME_NOT_SPECIFIED = 5
INI_FILENAME_NOT_FOUND = 6
FAILED_TO_MAKE_DIRECTORY = 7
VARIABLE_NOT_FOUND = 11
VARIABLE_NOT_SET = 12

UNKNOWN_ERROR = 13  # An unspecified exception was found
NO_DEFAULT_DATABASE = 41
CHILD_TERMINATED_BY_SIGNAL = 43

ANTLR_COMPILE_ERROR = 44
ANTLR_EXECUTION_FAILED = 44

OS_ERROR = 45
GIT_ERROR = 46

INAPPROPRIATE_DEPLOYMENT = 49

INVALID_BAK_TABLE_NAME = 57

WINDOWS_BACKSLASHES_USED = 78

UNKNOWN_DIR_SCAN_TYPE = 101
UNKNOWN_EXTENSION = 102

UDAEXEC_ERROR = 103

UNICODE_ERROR = 104

VIRTUAL_DB_EXECUTION_FAILED = 105

UNKNOWN_CHANGESET_TYPE = 106

INVALID_SEVERITY = 107

INVALID_SOURCE_NAME = 108

UNKNOWN_RULES_ENGINE_TYPE = 109

UNKNOWN_EXPECTED_OBJECT_TYPE = 110

ARRAY_INDEX_ERROR = 111

UNKNOWN_DATATYPE = 112

FAILED_TO_DOWNLOAD_FILE = 113

INVALID_TEMP_DIR = 114
INVALID_INPUT = 115
MODULE_NOT_FOUND = 116

DUPLICATE_FILES_INCLUDED = 117

INVALID_XML_CONTENTS = 118

TIMEOUT = 119

CURL_ERROR = 120

INVALID_SQL = 121
