package(default_visibility = ["PUBLIC"])

python_library(
    name = "Antlr",
    srcs = glob ([
        "Python3Lexer.py",
        "Python3LexerBase.py",
        "Python3Parser.py",
        "Python3ParserBase.py",
        ]),
    resources=[
        "DATABRICKS.g4",
        "DATABRICKS_Lexer.g4",
        "Python3Lexer.tokens",
        "TD16.g4",
        "TD15_comment_on.g4",
        ]
)
