--liquibase formatted sql

--changeset Wolfe:HSETL_WORK_DEV.DATAOPS_RULES_ENGINE_QUEEN_TABLE2 runAlways:false runOnChange:true labels:eds context:dev,test,prod
--comment: Create table HSETL_WORK_DEV.DATAOPS_RULES_ENGINE_QUEEN_TABLE2

------------------------------------------------------------------------------------------
CREATE MULTISET TABLE HSETL_WORK_DEV.DATAOPS_RULES_ENGINE_QUEEN_TABLE2,
    MAP = TD_MAP1  ( ETL_LOAD_DT_TM TIMESTAMP(0) NOT NULL DEFAULT CURRENT_TIMESTAMP(0),
      ARTIST CHAR(5) NOT NULL DEFAULT 'Queen',
      OH_MAMA_MIA VARCHAR(20) NOT NULL DEFAULT 'mama mia!',
      LET_ME_GO DATE,
      BEELZEBUB INTEGER,
      HAS_THE_DEVIL_PUT_ASIDE_FOR_ME VARCHAR(255) CHARACTER SET UNICODE NOT CASESPECIFIC,
      FOR_ME VARCHAR(50) CHARACTER SET UNICODE NOT CASESPECIFIC NOT NULL,
      FOR_MEEEEE INTEGER NOT NULL,
      GUITAR_SOLO VARCHAR(20) CHARACTER SET UNICODE NOT CASESPECIFIC NOT NULL
	  );


COLLECT STATISTICS
                   -- default SYSTEM SAMPLE PERCENT
                   -- default SYSTEM THRESHOLD PERCENT
            COLUMN ( GUITAR_SOLO ) ON HSETL_WORK_DEV.DATAOPS_RULES_ENGINE_QUEEN_TABLE2;

--rollback DROP TABLE HSETL_WORK_DEV.DATAOPS_RULES_ENGINE_QUEEN_TABLE2;