--liquibase formatted sql

--changeset Wolfe:HSETL_WORK_DEV.DATAOPS_RULES_ENGINE_QUEEN_TABLE runAlways:false runOnChange:true labels:eds context:dev,test,prod
--comment: Create table HSETL_WORK_DEV.DATAOPS_RULES_ENGINE_QUEEN_TABLE

------------------------------------------------------------------------------------------
CREATE MULTISET TABLE HSETL_WORK_DEV.DATAOPS_RULES_ENGINE_QUEEN_TABLE,
    MAP = TD_MAP1  ( ETL_LOAD_DT_TM TIMESTAMP(0) NOT NULL DEFAULT CURRENT_TIMESTAMP(0),
      ARTIST CHAR(5) NOT NULL DEFAULT 'Queen',
      IS_THIS_THE_REAL_LIFE? INTEGER NOT NULL,
      IS_THIS_JUST_FANTASY INTEGER,
      CAUGHT_IN_A_LANDSLIDE VARCHAR(255) CHARACTER SET UNICODE NOT CASESPECIFIC,
      NO_ESCAPE_FROM_REALITY! VARCHAR(50) CHARACTER SET UNICODE NOT CASESPECIFIC NOT NULL,
      OPEN_YOUR_EYES INTEGER NOT NULL,
      LOOK_UP_TO_THE_SKIES VARCHAR(20) CHARACTER SET UNICODE NOT CASESPECIFIC NOT NULL DEFAULT 'AND SEEEEEEE',
      IM_JUST_A_POOR_BOY VARCHAR NOT NULL DEFAULT 'I need no sympathy...',
      CUZ_IM VARCHAR(255) CHARACTER SET UNICODE NOT CASESPECIFIC DEFAULT 'Easy come, Easy go...',
      LITTLE_HIGH_LITTLE_LOW INTEGER,
      ANYWHERE_THE_WIND_BLOWS TIME,
      DOESNT_REALLY_MATTER varchar,
      TO_ME varchar(255) NOT NULL DEFAULT 'PIANO_INTERLUDE'
	  )
PRIMARY INDEX ( ARTIST, ETL_LOAD_DT_TM);


COLLECT STATISTICS
                   -- default SYSTEM SAMPLE PERCENT
                   -- default SYSTEM THRESHOLD PERCENT
            COLUMN ( ARTIST, ETL_LOAD_DT_TM ) ON HSETL_WORK_DEV.DATAOPS_RULES_ENGINE_QUEEN_TABLE;

--rollback DROP TABLE HSETL_WORK_DEV.DATAOPS_RULES_ENGINE_QUEEN_TABLE;