name: Cleanup Feature Branch

on: delete

permissions:
  contents: read
  id-token: write
  checks: write

jobs:
  FeatureCleanup:
    name: Cleanup Feature Branch
    if: ${{ github.event.ref_type == 'branch' }}
    uses: ./.github/workflows/deploy.yaml
    with:
      environment: dev
      action: destroy
    secrets: inherit
