name: Pull Request Actions

on:
  pull_request:
    branches:
      - main
    types:
      - opened
      - synchronize
      - reopened
      - ready_for_review

permissions:
  contents: write
  id-token: write

jobs:
  ValidPlan:
    if: github.event.pull_request.draft == false
    uses: ./.github/workflows/deploy.yaml
    with:
      environment: dev
      action: plan
    secrets: inherit
